### ISSUE TITLE
cuda or not

### ISSUE THREAD

**Issue by KrisThielemans** [conda-forge/parallelproj-feedstock#11]
### Comment:

I did `mamba create -n parallelproj parallelproj` on my Linux VM which doesn't have nvidia drivers, and get the openmp and CUDA libraries of parallelproj. Indeed, `parallelprojConfig.cmake` says
```
find_package(OpenMP REQUIRED)

if(NOT FALSE)
  set(parallelproj_built_with_OpenMP TRUE)
endif()

if(NOT FALSE)
  set(parallelproj_built_with_CUDA TRUE)
endif()

if(FALSE)
  set(parallelproj_built_with_IDL_wrappers TRUE)
endif()
```
This might be fine, but STIR then tries to run the CUDA version, which I presume it cannot (I haven't checked yet). This also happens on [conda-forge for Windows](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=653848&view=logs&jobId=d0d954b5-f111-5dc4-4d76-03b6c9d0cf7e&j=171a126d-c574-5c8c-1269-ff3b989e923d&t=1183ba29-a0b5-5324-8463-2a49ace9e213&l=26288)
```
-- Found parallelproj 1.2.13 (will use its CUDA support)
```
(The tests there succeed, but they're not running anything that uses `parallelproj` as I'm not running CTest as part of the build script. Maybe I should...)

Not sure what to do with this... To me it feels that the `mambda create` should have checked if it'd made sense to have the CUDA version or not, and download whatever is appropriate.

**Comment by gschramm** [comment]
Hi Kris,

I just tried the same with conda (not mamba) on my local Mac ans a server running Ubuntu 18.04 - both without CUDA.
In both cases the non-CUDA versions get installed and the cmake config looks as expected (shown) below.

So I'd guess it is a problem with mamba. A similar bug in mamba is reported [here](https://github.com/mamba-org/mamba/issues/1542).

```
if(NOT FALSE)
  set(parallelproj_built_with_OpenMP TRUE)
endif()

if(NOT TRUE)
  set(parallelproj_built_with_CUDA TRUE)
endif()

if(FALSE)
  set(parallelproj_built_with_IDL_wrappers TRUE)
endif()
``

**Comment by KrisThielemans** [comment]
`conda-forge` uses `mamba`, so this seems to prevent me to merge https://github.com/conda-forge/stir-feedstock/pull/67

**Comment by gschramm** [comment]
Hm, indeed a bit anoying. I just asked for help on the conda-forge gitter channel.

**Comment by gschramm** [comment]
Hi Kris,

after feedback from Mark Harfouche (matrix.org), it seem that is we link against against ```parallelproj_cuda.so``` in the build of STIR (on systems with cuda), and against ```parallelproj_c.so``` on systems without cuda, we also need separate STIR cuda and non-cuda versions.

I will create a fork of your stir feedstock to see how that could work.

**Comment by gschramm** [comment]
after a quick and dirty test with a PR (that I already closed again), could you try to modify the requirements section to:
```
requirements:
  host:
    - parallelproj *=cpu*  # [cuda_compiler_version == "None"]
    - parallelproj *=cuda*  # [cuda_compiler_version != "None"]
```

This should force the installation of the parallelproh cpu version when cuda is not present, and also force the parallelproh cuda version when cuda is present.

If that works, we also need to adapt the build strings similar to what I use in parallelproh to reflect whether STIR was build with or without cuda.

**Comment by KrisThielemans** [comment]
done. I've also added `ctest` in the STIR feedstock build to catch errors.

**Comment by KrisThielemans** [comment]
> If that works, we also need to adapt the build strings similar to what I use in parallelproh to reflect whether STIR was build with or without cuda.

is that these lines?
https://github.com/conda-forge/parallelproj-feedstock/issues/11#issuecomment-1435781133

Anything else? I think best way might be for you to do a PR really.

**Comment by KrisThielemans** [comment]
Doesn't seem to have worked, as both Win and Linux still want cuda builds. (The OSX build now fails as I didn't exclude the cuda version on osx).

maybe should go all the way and do what you did.

**Comment by gschramm** [comment]
Interesting ... In my quick and dirty fork + PR 
https://github.com/conda-forge/stir-feedstock/pull/69/files

I enforced the `cpu` version of `parallelproj` (no cuda builds at all).
This indeed seems to install the `cpu` version of `parallelproj` in the builds
see e.g. line 145 [here](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=660977&view=logs&j=d0d954b5-f111-5dc4-4d76-03b6c9d0cf7e&t=841356e0-85bb-57d8-dbbc-852e683d1642)

The build fails later, but this is probably since I only quickly hacked `meta.yaml`

I guess this somehow shows that test on the `cuda_compiler_version == None` did not work for you

**Comment by gschramm** [comment]
To move forward, I suggest:
1. we make sure that the CPU-only build of STIR on conda-forge works (by always forcing the cpu version of parallelproj)
2. once 1. works,  we try the additional GPU builds (probably with the support of a few conda-forge guys).

For 2., we need to:
- have dedicated build strings for cuda/cpu versions similar to [here](https://github.com/conda-forge/parallelproj-feedstock/blob/3f25fed8247c316170b672d8f4029bff57d3389c/recipe/meta.yaml#L19)
- make sure that all tests that would use `libparallelproj_cuda.so` in a cuda build are not run when there is no physical GPU present

**Comment by KrisThielemans** [comment]
1. should be done soon.
2. you have some other stuff in your files that we don't have, so might take a bit more work. However, STIR detects if parallelproj-CUDA is present or not, and does calls "parallelproj" either the OpenMP or CUDA version, so we wouldn't need any checks there.
