### ISSUE TITLE
depending on parallelproj might create a problem for C++ build

### ISSUE THREAD

**Issue by KrisThielemans** [conda-forge/parallelproj-feedstock#41]
I was trying to make a dev version for stir-feedstock at https://github.com/conda-forge/stir-feedstock/pull/79 but hadn't updated the recipe to use libparallelproj yet.

I got some surprising build errors. Extracing lines from https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=701585&view=logs&jobId=b14d9056-66e9-58f5-fe70-f09b2dad5d2c&j=d0d954b5-f111-5dc4-4d76-03b6c9d0cf7e&t=841356e0-85bb-57d8-dbbc-852e683d1642:
- Conda package stuff
```
libparallelproj:                      1.3.7-cuda111_h12f7317_200      conda-forge
parallelproj:                         1.3.5-cuda110_py310h5096daf_201 conda-forge
```
-  STIR CMake stuff
```
-- Found parallelproj 1.3.7 (will use its CUDA support)
```
- Conda checks
```
2023-05-05T22:56:37.6344803Z WARNING (stir,bin/generate_image): Needed DSO lib/libparallelproj_cuda.so.1.3.7 found in ['libparallelproj']
2023-05-05T22:56:37.6345772Z WARNING (stir,bin/generate_image): .. but ['libparallelproj'] not in reqs/run, (i.e. it is overlinking) (likely) or a missing dependency (less likely)
```
- errors during running
```
import stir
   from _stir import *
     ImportError: libparallelproj_cuda.so.1.3.7: cannot open shared object file: No such file or directory
```

It seems that requiring parallelproj  in `host` got a version mismatch, and that running it didn't install `libparallelproj`. (I still don't understand the `host`/ `test` /` run` stuff sadly).

This could be partly because of the cuda trickery we had before, but the last bit doesn't seem to have anything to do with that.

I've now modified the STIR PR to use `libparallelproj`
https://github.com/conda-forge/stir-feedstock/pull/79/commits/0ce25b428935e1b4ebc6faabf3d59101bd9bd821
and likely all problems disappear, but it could point to some underlying problems in this feedstock, so I thought I'd post it here. Feel free to close.

**Comment by KrisThielemans** [comment]
I should have added that `parallelproj` was not installed by conda for the tests, hence the run-time failure

**Comment by KrisThielemans** [comment]
> I've now modified the STIR PR to use libparallelproj https://github.com/conda-forge/stir-feedstock/commit/0ce25b428935e1b4ebc6faabf3d59101bd9bd821 and likely all problems disappear,

they did

**Comment by gschramm** [comment]
@KrisThielemans  Completely missed that one.
If I understand correctly, right now there is no issue for Stir when requiring libparallelproj?

**Comment by KrisThielemans** [comment]
correct. I haven't tried going back to depending on `parallelproj`. There are far more pressing things to look into though, and as it all works now, probably best to close this.
